name: Setup
description: Setups latest Node LTS and installs dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: npm
        check-latest: true
        node-version: 16
    - name: Install Dependencies
      run: npm ci
      shell: bash
