title: React Children Utilities
description: Recursive and extended utils for React children opaque data structure.
url: https://fernandopasik.com

main_nav:
  - title: Getting Started
    url: /getting-started
  - title: API
    url: /api

content_table:
  - title: Getting Started
    url: /getting-started
  - title: API
    url: /api
    links:
      - title: deepFilter
        url: /deep-filter
      - title: deepFind
        url: /deep-find
      - title: deepForEach
        url: /deep-foreach
      - title: deepMap
        url: /deep-map
      - title: filter
        url: /filter
      - title: getElementName
        url: /get-element-name
      - title: groupByType
        url: /group-by-type
      - title: hasChildren
        url: /has-children
      - title: hasComplexChildren
        url: /has-complex-children
      - title: onlyText
        url: /only-text
      - title: onlyValid
        url: /only-valid

google_analytics: G-2MWB7NGC05

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
